AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'lib/features.rb'

Metrics/LineLength:
  Max: 100

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
